# Generated by Django 3.2.7 on 2021-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='hobbiesApp.Hobby'),
        ),
    ]
