# Generated by Django 3.2.7 on 2021-12-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbiesApp', '0003_myuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
    ]
